---

- name: Ensure git is installed (Debian).
  apt:
    name: git
    state: installed
  when: (git_install_from_source == false) and (ansible_os_family == 'Debian')

# Install git from source when git_install_from_source is true.
- include: install-from-source.yml
  when: git_install_from_source == true
