---

- name: Import public key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

# Need to split this line and the next into two using a variable
- name: Create sources list file
  sudo: yes
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse"
  register: source_list

- name: Create source list for mongodb
  copy: content="{{ source_list.stdout }}" dest=/etc/apt/sources.list.d/mongodb-org-3.2.list
  sudo: yes

- name: Update cache
  sudo: yes
  apt: update_cache=yes

- name: Install MongoDB
  sudo: yes
  apt: name=mongodb-org

- name: Replace mongo config with development config
  sudo: yes
  template: src=etc/mongod-dev.j2 dest=/etc/mongod.conf
  when: production == false
  notify:
    - restart mongodb

- name: Replace mongo config with staging config
  sudo: yes
  template: src=etc/mongod-staging.j2 dest=/etc/mongod.conf
  when: staging == True
  notify:
    - restart mongodb

- name: Start MongoDB
  sudo: yes
  service:
    name: mongod
    state: started

# Service seems to not be working in some servers
- name: Upload run_db script
  copy: src=run_db.sh dest=/home/ubuntu/run_db.sh mode=0777

- name: Make sure DB is always running
  cron: name="run_db" job="/bin/bash /home/ubuntu/run_db.sh"
