---
  - name: Create app server security group
    local_action:
      module: ec2_group
      name: sg_loganswalk_app_srv
      description: Loganswalk app servers
      region: us-east-1
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          from_port: 1
          to_port: 49151
          cidr_ip: 0.0.0.0/0

  - name: Launch an instance
    local_action:
      module: ec2
      region: us-east-1
      keypair: loganswalk_ec2
      group: sg_loganswalk_app_srv
      instance_type: t2.micro
      image: ami-9eaa1cf6
      count: 1
      wait: yes
    register: ec2

  - name: Add instances to local host group
    local_action: add_host hostname={{ item.public_ip }} groupname=sg_loganswalk_app_srv
    with_items: ec2.instances

  - name: Write new instance to local hosts file
    local_action: lineinfile dest=inventory/hosts regexp="{{ item.public_dns_name }}" insertafter="[app_servers]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
    with_items: ec2.instances
    #"

  - name: Add tag to instances
    local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
    with_items: ec2.instances
    args:
      tags:
        Name: Loganswalk

  - name: Wait for SSH to become available
    pause: seconds=45